name: "Shopify Preview Axe A11y Report"
description: "Run axe accessibility tests on Shopify preview URLs from PR description and comment results."

inputs:
  edit_bot_comment:
    description: "Edit the last bot comment instead of creating a new one"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install dependencies
      shell: bash
      run: |
        npm install -g @axe-core/cli browser-driver-manager
        BROWSER_DRIVER_OUTPUT=$(npx browser-driver-manager install chrome)
        echo "BROWSER_DRIVER_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$BROWSER_DRIVER_OUTPUT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Run accessibility checks
      shell: bash
      run: node "${{ github.action_path }}/scripts/run-axe-tests.js"
      env:
        GITHUB_EVENT_NAME: "${{ github.event_name }}"
        PR_BODY: "${{ github.event.pull_request.body }}"
        DEBUG: "${{ runner.debug == '1' }}"
        BROWSER_DRIVER_OUTPUT: ${{ env.BROWSER_DRIVER_OUTPUT }}

    - name: Generate PR comment markdown
      shell: bash
      run: node "${{ github.action_path }}/scripts/generate-axe-comment.js"
      env:
        DEBUG: "${{ runner.debug == '1' }}"

    - name: Comment on PR with results
      if: ${{ github.event.pull_request.state == 'open' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const commentBody = fs.readFileSync('axe-comment.md', 'utf8');
          const editBotComment = '${{ inputs.edit_bot_comment }}' === 'true';
          
          if (editBotComment) {
            // Find the last comment from this bot
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100
            });
            
            const botComment = comments.data
              .filter(comment => comment.user.login === 'github-actions[bot]')
              .pop();
            
            if (botComment) {
              console.log(`Editing existing comment #${botComment.id}`);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody,
              });
            } else {
              console.log('No existing bot comment found, creating new comment');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }
          } else {
            console.log('Creating new comment');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });
          }
